server:
  port: 8888

eureka:
  instance:
    hostname: config
    prefer-ip-address: true #注册时用IP地址
    metadata-map:
      user:
        name: ${security.user.name}
        password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YuGanRepo/sc-example
          search-paths: config-repo
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}





